-- =====================================================================
-- SQUASHED INTO BASELINE - intentionally a no-op.
--
-- Seluruh objek yang dibuat migrasi ini (tenants, tenant_memberships,
-- tenant_r2_connections, r2_files, fungsi current_tenant_id /
-- has_tenant_access / assign_and_validate_tenant_scope /
-- validate_r2_file_scope, trigger, policy, RLS) sudah termuat dalam
-- 20260101000000_baseline_schema.sql (snapshot skema owner live).
--
-- Migrasi ini memakai CREATE TRIGGER/POLICY tanpa guard DROP IF EXISTS,
-- sehingga memutarnya ulang di atas baseline penuh akan gagal dengan
-- "already exists". Instalasi lama (owner/kozoo) sudah mencatat versi
-- ini di supabase_migrations.schema_migrations, jadi tetap dilewati.
--
-- Original content: see git history.
-- =====================================================================
