-- =====================================================================
-- SQUASHED INTO BASELINE - intentionally a no-op.
--
-- This migration effect is already included in
-- 20260101000000_baseline_schema.sql (snapshot of the live production
-- schema). Kept so existing installations, whose migration history
-- already contains this version, remain valid.
--
-- Original content: see git history.
-- =====================================================================
